name: Prod Deployment

on:
  push:
    branches: [ master]

jobs:
  prod-deploy:
    name: "Validate & deploy bundle to prod"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # - name: Install Databricks CLI
      #   run: |
      #     pip install --upgrade pip
      #     pip install databricks
      #     pip install databricks-sdk

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Check Databricks CLI version
        run: databricks version

      # Validate is implicit in deploy, but you can separate if you want
      - name: Deploy bundle to prod
        run: databricks bundle deploy
        working-directory: .
        env:
          DATABRICKS_HOST: "https://dbc-2717eb51-11b4.cloud.databricks.com" # ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: "dapi0b90879f3db4fa2b0e57cc68ee849fd6" # # ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
  
  prod-run:
    name: "Run medallion_pipeline (prod)"
    runs-on: ubuntu-latest
    needs: prod-deploy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Run finalProject_pipeline job
        run: databricks bundle run finalProject_pipeline --refresh-all
        working-directory: .
        env:
          DATABRICKS_HOST: "https://dbc-2717eb51-11b4.cloud.databricks.com" # ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: "dapi0b90879f3db4fa2b0e57cc68ee849fd6" # ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
