name: CD

on:
  push:
    branches: [ master, feature/cicd ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Databricks SDK + CLI
        run: |
          pip install databricks-cli databricks-sdk
      
      

      - name: Sync GitHub â†’ Databricks Repo
        env:
          DATABRICKS_HOST: "https://dbc-2717eb51-11b4.cloud.databricks.com"
          # ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: "dapi0b90879f3db4fa2b0e57cc68ee849fd6"
          # ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks repos update --path /Repos/you/project --branch main



      - name: Deploy Bundle to Workspace
        env:
          DATABRICKS_HOST: "https://dbc-2717eb51-11b4.cloud.databricks.com"
          # ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: "dapi0b90879f3db4fa2b0e57cc68ee849fd6"
          # ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks bundle deploy
          databricks bundle run medallion_pipeline
