name: Dev Deployment

# on:
#   pull_request:
#     branches: [ master, feature/cicd ]
#   push:
#     branches: [ master, feature/cicd ]

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master

jobs:
  dev-deploy:
    name: "Validate & deploy bundle to dev"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # - name: Install Databricks CLI
      #   run: |
      #     pip install --upgrade pip
      #     pip install databricks
      #     pip install databricks-sdk

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Check Databricks CLI version
        run: databricks version

      # Validate is implicit in deploy, but you can separate if you want
      - name: Deploy bundle to dev
        run: databricks bundle deploy
        working-directory: .
        env:
          # sayed
          DATABRICKS_HOST: "https://dbc-2717eb51-11b4.cloud.databricks.com" # ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: "dapi0b90879f3db4fa2b0e57cc68ee849fd6" # # ${{ secrets.DATABRICKS_TOKEN }}
          # alex
          # DATABRICKS_HOST: "https://dbc-80b67b69-d5ca.cloud.databricks.com"
          # DATABRICKS_TOKEN: "dapi987cbb78ad45d4640cdc51af191dc63d"
          # daniel
          # DATABRICKS_HOST: "https://dbc-f37ae718-1631.cloud.databricks.com" # ${{ secrets.DATABRICKS_HOST }}
          # DATABRICKS_TOKEN: "dapi0b90879f3db4fa2b0e57cc68ee849fd6" # # ${{ secrets.DATABRICKS_TOKEN }}

          DATABRICKS_BUNDLE_ENV: dev
  
  dev-run:
    name: "Run medallion_pipeline (dev)"
    runs-on: ubuntu-latest
    needs: dev-deploy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Run finalProject_pipeline job
        run: databricks bundle run finalProject_pipeline --refresh-all
        working-directory: .
        env:
          # sayed
          DATABRICKS_HOST: "https://dbc-2717eb51-11b4.cloud.databricks.com" # ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: "dapi0b90879f3db4fa2b0e57cc68ee849fd6" # # ${{ secrets.DATABRICKS_TOKEN }}
          # alex
          # DATABRICKS_HOST: "https://dbc-80b67b69-d5ca.cloud.databricks.com"
          # DATABRICKS_TOKEN: "dapi987cbb78ad45d4640cdc51af191dc63d"
          # daniel
          # DATABRICKS_HOST: "https://dbc-f37ae718-1631.cloud.databricks.com" # ${{ secrets.DATABRICKS_HOST }}
          # DATABRICKS_TOKEN: "dapi0b90879f3db4fa2b0e57cc68ee849fd6" # # ${{ secrets.DATABRICKS_TOKEN }}

          DATABRICKS_BUNDLE_ENV: dev
